# -*- coding: utf-8 -*-
"""This module contains default config bindings"""
DEFAULT_FIELDNAMES = [
    "Abstract",
    "Access",
    "Availability",
    "External Resources",
    "Find Items About",
    "Title",
    "Publication",
    "Author(s)",
    "Corp Author(s)",
    "Publication",
    "Year",
    "Description",
    "Dissertation",
    "Language",
    "ISBN",
    "Genre/Form",
    "Materials specified",
    "Identifier",
    "Action Note",
    "Note(s)",
    "Descriptor",
    "Geographic",
    "General Info",
    "Class Descriptors",
    "Other Titles",
    "Responsibility",
    "Material Type",
    "Document Type",
    "Date of Entry",
    "Update",
    "Accession No",
    "Provider",
    "Database",
]

DEFAULT_LIST_TAGS = [
    "Access",
    "Genre/Form",
    "Geographic",
    "Descriptor",
]
